### ISSUE TITLE
可变数组取值，越界判断有误

### ISSUE THREAD

**Issue by UncleWang1992** [GentleForYou/Runtimer-Demo#1]
NSMutableArray+Swizzling.m
正确的为

- (id)safeObjectAtIndex:(NSUInteger)index {
    if (self.count == 0) {
#if DEBUG
        NSLog(@"%s can't get any object from an empty array", __FUNCTION__);
#endif
        return nil;
    }
    if (index >= self.count) {
#if DEBUG
        NSLog(@"%s index out of bounds in array", __FUNCTION__);
#endif
        return nil;
    }
    return [self safeObjectAtIndex:index];
}

**Comment by GentleForYou** [comment]
收到，谢谢。
已修改
